#!/usr/bin/env python3
"""Regenerate src/lib/fighterSprites.ts from the Level 7 BBC Micro disassembly.

Usage: python3 scripts/decode-bbc-sprites.py <disassembly.txt> [out.ts]
  The disassembly: https://www.level7.org.uk/miscellany/the-way-of-the-exploding-fist-disassembly.txt

Sprite format (from the game's plotter): a 3-byte header (max_x, top_group, min_x), then
(9 - top_group) groups of (max_x - min_x) bytes, bottom group first. Each group is one
8-row character row of MODE 5 screen memory: byte i covers cell i>>3, row i&7, and holds
four 2-bit pixels (bits 7-n and 3-n for pixel n). Bytes are read sequentially after the
header because one address label in the listing is a typo.
"""
import re
import sys

src = sys.argv[1]
out = sys.argv[2] if len(sys.argv) > 2 else 'src/lib/fighterSprites.ts'
lines = open(src).read().split('\n')
hexline = re.compile(r'^&([0-9a-f]{4}) ((?:[0-9a-f]{2} ?)+)')

sprites = {}
for i, ln in enumerate(lines):
    m = re.match(r'^; sprite_([0-9a-f]{2})_data \((SPRITE_\w+)\)', ln)
    if not m:
        continue
    idx = int(m.group(1), 16)
    name = m.group(2)
    hb = [int(b, 16) for b in hexline.match(lines[i + 1]).group(2).split()]
    max_x, top_group, min_x = hb[0], hb[1], hb[2]
    width = max_x - min_x
    groups = 9 - top_group
    need = width * groups
    data = hb[3:]
    j = i + 2
    while len(data) < need and j < len(lines):
        m2 = hexline.match(lines[j])
        if m2:
            rest = lines[j][m2.end():].strip()
            if not rest or rest.startswith(';') or rest.startswith('#'):
                data += [int(b, 16) for b in m2.group(2).split()]
        elif lines[j].startswith('; sprite_'):
            break
        j += 1
    data = data[:need]
    grid = [[0] * 36 for _ in range(72)]
    for g in range(groups):
        for k, byte in enumerate(data[g * width:(g + 1) * width]):
            y_off = min_x + k
            cell, row = y_off >> 3, y_off & 7
            py = (8 - g) * 8 + row
            for n in range(4):
                grid[py][cell * 4 + n] = ((byte >> (7 - n)) & 1) << 1 | ((byte >> (3 - n)) & 1)
    sprites[idx] = (name, grid)

lines_out = ['''/**
 * Fighter sprites for Way of the Exploding Sats.
 *
 * These are the 44 karateka poses from the BBC Micro conversion of The Way of the
 * Exploding Fist (Melbourne House, 1985, converted by Michael Simpson), decoded from
 * the MODE 5 (2 bits per pixel) sprite tables documented in the Level 7 disassembly
 * (https://www.level7.org.uk/miscellany/the-way-of-the-exploding-fist-disassembly.txt).
 * Each sprite is 36 x 72 MODE 5 pixels (a MODE 5 pixel is twice as wide as it is tall),
 * stored as rows of colour indices: 0 = transparent, 1 = gi, 2 = skin, 3 = hair/shadow.
 * Rows above `top` are empty and omitted. The artwork remains the copyright of its
 * original creators and is reproduced here for this non-commercial tribute.
 *
 * Generated by scripts/decode-bbc-sprites.py - do not edit by hand.
 */

export const SPRITE_WIDTH = 36;
export const SPRITE_HEIGHT = 72;

export interface SpriteData {
  name: string;
  /** first non-empty row (0..71) */
  top: number;
  /** rows from `top` to 71, each a string of 36 digits 0-3 */
  rows: string[];
}

export const SPRITES: Record<number, SpriteData> = {''']
for idx in sorted(sprites):
    name, grid = sprites[idx]
    top = next((y for y in range(72) if any(grid[y])), 72)
    lines_out.append(f"  0x{idx:02x}: {{ name: '{name[7:]}', top: {top}, rows: [")
    for y in range(top, 72):
        lines_out.append("    '" + ''.join(str(v) for v in grid[y]) + "',")
    lines_out.append('  ] },')
lines_out.append('};')
lines_out.append('''
export const S = {
  STANDING: 0x00, KICK_ONE: 0x01, SHORT_JAB_KICK: 0x02, KICK_TWO: 0x03, MID_KICK: 0x04, HIGH_KICK: 0x05,
  SWEEP_ONE: 0x06, SWEEP_TWO: 0x07, CROUCHING_JAB: 0x08, PREPARING_TO_PUNCH: 0x09, STANDING_JAB: 0x0a,
  HIGH_PUNCH: 0x0b, CROUCH: 0x0c, LOW_BLOCK: 0x0d, HIGH_BLOCK: 0x0e, BENDING_KNEES: 0x0f, JUMPING: 0x10,
  FLYING_KICK: 0x11, HIGH_BACK_KICK_ONE: 0x12, HIGH_BACK_KICK_TWO: 0x13, ROUNDHOUSE_ONE: 0x14,
  ROUNDHOUSE_TWO: 0x15, ROUNDHOUSE_THREE: 0x16, ROUNDHOUSE_FOUR: 0x17, REACHING_KICK: 0x18,
  SOMERSAULT_ONE: 0x19, SOMERSAULT_TWO: 0x1a, SOMERSAULT_THREE: 0x1b, SOMERSAULT_FOUR: 0x1c,
  SOMERSAULT_FIVE: 0x1d, WALKING_ONE: 0x1e, WALKING_TWO: 0x1f, WALKING_THREE: 0x20,
  BOW_SIDEWAYS_ONE: 0x28, BOW_SIDEWAYS_TWO: 0x29, FACE_FORWARDS: 0x2a, BOW_FORWARDS: 0x2b,
  FALLING_BACKWARDS_ONE: 0x2c, FALLING_BACKWARDS_TWO: 0x2d, FALLEN_BACKWARDS: 0x2e,
  FALLING_FORWARDS_ONE: 0x2f, FALLING_FORWARDS_TWO: 0x30, FALLEN_FORWARDS: 0x31, FALLEN_INWARDS: 0x32,
} as const;
''')
open(out, 'w').write('\n'.join(lines_out) + '\n')
print(f'{len(sprites)} sprites written to {out}')
